### ISSUE TITLE
MQTT QoS1 via AsyncMqttClient by Marvin ROGER

### ISSUE THREAD

**Issue by afons0** [afons0/pzmesp-energymonitor#1]
Implement MQTT Publish with QoS 1 via AsyncMqttClient in order to not lose data while broker is unavailable.

**Comment by 0raculo** [comment]
This won't work without writing values to flash which will wear it out quite fast.
Goal for this issue was to ensure buffering if broker is unavailable. ESP8266 won't do this reliably.
